# -*- coding: utf-8 -*-
from pkan.dcatapde import _


DEFAULT_LANGUAGE = u'gbr'

AVAILABLE_LANGUAGES_ISO = {
    u'de': u'deu',
    u'us': u'usa',
    u'gb': u'gbr',
    u'uk': u'gbr',
    u'en': u'eng',
    u'et': u'eth',
    u'da': u'dan',
    u'fi': u'fin',
    u'lt': u'lit',
    u'nl': u'nld',
    u'ro': u'ron',
    u'fr': u'fra',
    u'cs': u'ces',
    u'lv': u'lav',
    u'pt': u'por',
    u'sl': u'slv',
    u'es': u'spa',
    u'mt': u'mlt',
    u'it': u'ita',
    u'hu': u'hun',
    u'sv': u'swe',
    u'no': u'nor',
    u'ga': u'gle',
    u'bg': u'bul',
    u'hr': u'hrv',
    u'el': u'ell',
    u'sk': u'slk',
    u'pl': u'pol',
}

AVAILABLE_LANGUAGES_TITLE = {
    u'deu': _(u'German'),
    u'usa': _(u'English (USA)'),
    u'gbr': _(u'Egnlish (GB)'),
    u'eth': _(u'Ethiopia'),
    u'eng': _(u'English'),
    u'dan': _(u'Danish'),
    u'fin': _(u'Finnish'),
    u'lit': _(u'Lithuanian'),
    u'nld': _(u'Dutch'),
    u'ron': _(u'Romanian'),
    u'fra': _(u'French'),
    u'ces': _(u'Czech'),
    u'lav': _(u'Latvian'),
    u'por': _(u'Portuguese'),
    u'slv': _(u'Slovak'),
    u'spa': _(u'Spanish'),
    u'mlt': _(u'Maltese'),
    u'ita': _(u'Italian'),
    u'hun': _(u'Hungarian'),
    u'swe': _(u'Swedish'),
    u'nor': _(u'Norwegian'),
    u'gle': _(u'Irish'),
    u'bul': _(u'Bulgarian'),
    u'hrv': _(u'Croation'),
    u'ell': _(u'Modern Greek'),
    u'slk': _(u'Slovak'),
    u'pol': _(u'Polish'),
}
